version: '2.1'
networks: {}
volumes:
  resin-data: {}
services:
  main:
    build:
      context: .
    # We will ignore this message for now:
    # "Unable to start udev, container must be run in privileged mode to start udev!"
    # privileged: true
    restart: always

    ## networking
    # network_mode: host
    ports:
      - "80:80"
    ##

    volumes:
      - 'resin-data:/data'
    labels:
      # io.balena.features.kernel-modules: '1'
      # io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      # io.balena.features.supervisor-api: '1'
      # io.balena.features.balena-api: '1'
